controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ContactForm;
use app\models\LoginForm;
use app\models\PasswordResetRequestForm;
use app\models\ResetPasswordForm;
use app\models\SignupForm;
use Yii;
use yii\base\InvalidParamException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use app\models\User;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionDonate()
    {
        return $this->render('donate');
    }

    public function actionTeam()
    {
        return $this->render('team');
    }

    public function actionTermsOfUse()
    {
        return $this->render('terms-of-use');
    }

    public function actionPrivacyPolicy()
    {
        return $this->render('privacy-policy');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    $user->sendConfirmationEmail($user);
                    Yii::$app->session->setFlash('success', 'Check your email for confirmation.');
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            }

            Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     *
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionAccount()
    {
        $model = Yii::$app->user->identity;

        return $this->render('account', ['model' => $model]);
    }

    public function actionConfirm($id, $auth_key)
    {
        $user = User::findOne([
            'id' => $id,
            'auth_key' => $auth_key,
        ]);
        if (!empty($user)) {
            $user->is_email_confirmed = true;
            $user->status = User::STATUS_ACTIVE;
            $user->save();
            Yii::$app->session->setFlash('success', 'Your email has been successfully confirmed.');
        }

        return $this->goHome();
    }

    public function actionResendConfirmationEmail()
    {
        $user = Yii::$app->user->identity;
        if ($user->sendConfirmationEmail($user)) {
            Yii::$app->session->setFlash('success', 'Check your email for confirmation.');
        }

        return $this->goHome();
    }

    /**
     * Change the actual language, saving it on a cookie
     * @param $lang String The language to be set
     * @return Redirect to the previous page or if is not set, to the home page
     */
    public function actionChangeLanguage($lang)
    {
        $language = \app\models\Language::find($lang)->one();

        if ($language != NULL) {
            $cookies = Yii::$app->response->cookies;

            $langCookie = new \yii\web\Cookie([
                'name' => 'language',
                'value' => $lang,
            ]);

            $cookies->add($langCookie);

            return $this->redirect(Yii::$app->request->referrer ?: Yii::$app->homeUrl);
        }
    }

    public function actionDesignList()
    {
        return $this->render('design-list');
    }

    public function actionDesignView()
    {
        return $this->render('design-view');
    }

    public function actionDesignEdit()
    {
        return $this->render('design-edit');
    }
}

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model ContactForm */

use app\models\ContactForm;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Html;

$this->title = 'Contact';
?>
<?php $this->beginBlock('content-header-data'); ?>
<?php $this->endBlock(); ?>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>
            <div class="card-body">
                <p>If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.</p>
                <div class="form-group">
                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'email') ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'subject') ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>
                </div>
            </div>

            <div class="card-footer">
                <div class="form-group">
                    <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/design-edit.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('menu', 'Edit design');
?>
<div class="site-design-edit">
<p>
    Place content here
</p>

views/site/design-list.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('menu', 'Design List');
?>
<div class="site-design-list">
<p>
    Place content here
</p>

views/site/design-view.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

$this->title = Yii::t('menu', 'View design');
?>
<div class="site-design-view">
<p>
    Place content here
</p>

views/site/donate.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

$this->title = 'Donate';
?>
<div class="site-contact">
<p>
    OpenSourceWebsite is entirely supported by the general public.
</p>

<p>
    Your donations increase your social rating on this Website. Your donations pay for staff, servers, bandwidth, maintenance, development and protective infrastructure.
</p>

<h4>PayPal and credit cards</h4>

<p>
    <ul>
        <li>Processing with <?= Html::a('PayPal.Me', 'https://paypal.me/opensourcewebsite') ?></li>
    </ul>
</p>

<h4>Credit cards</h4>

<p>
    <ul>
        <li>Processing with <?= Html::a('SnowballFundraising.com', 'https://opensourcewebste.snwbll.com/giving-portal') ?></li>
    </ul>
</p>

<h4>Cryptocurrencies</h4>

<p>
    <ul>
        <li>50+ cryptocurrencies. Processing with <?= Html::a('CoinGate.com', 'https://coingate.com/pay/opensourcewebsite') ?></li>
        <li>4 cryptocurrencies. Processing with <?= Html::a('Coinbase.com', 'https://commerce.coinbase.com/checkout/e89005ec-c8c2-47c1-9ca4-b1deb9992794') ?></li>
    </ul>
</p>

<p>
    For questions and suggestions, please <a href="/contact">contact</a> us.
</p>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */

/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

?>

<p>
    OpenSourceWebsite (OSW) <?= Yii::t('app', 'is an open source website for the world\'s largest online social community. The Website is managed by users. The Website is updated after each code change. So everyone can influence how the Website works.') ?>
</p>

<p>
    <?= Yii::t('app', 'The Website will look like and what functions it will have depends only on the users\' decisions. This Website supports and develops ideas of E-democracy (also known as digital democracy or Internet democracy).') ?>
</p>

<p>
    <?= Yii::t('app', 'We want the Web to be even better. We want more people using it for more things. We want it to continue to drive creativity, education and economic growth. And we want to empower people to help shape the Web as they move more of their lives online.') ?>
</p>

<p>
    <?php if (!Yii::$app->user->isGuest && !Yii::$app->user->identity->is_email_confirmed) : ?>
    <?php echo Html::a('Resend Confirmation Email', ['site/resend-confirmation-email'], ['class' => 'btn btn-primary']); ?>
    <?php endif; ?>
</p>

<h4>Technologies</h4>

<ul>
    <li><?= Html::a('PHP 7', 'https://en.wikipedia.org/wiki/PHP') ?></li>
    <li><?= Html::a('Yii 2 PHP Framework', 'https://en.wikipedia.org/wiki/Yii') ?></li>
    <li><?= Html::a('JavaScript', 'https://en.wikipedia.org/wiki/JavaScript') ?></li>
    <li><?= Html::a('Vue.js 2 JavaScript Framework', 'https://en.wikipedia.org/wiki/Vue.js') ?></li>
    <li><?= Html::a('HTML 5', 'https://en.wikipedia.org/wiki/HTML') ?></li>
    <li><?= Html::a('CSS 3', 'https://en.wikipedia.org/wiki/Cascading_Style_Sheets') ?></li>
    <li><?= Html::a('MySQL 5', 'https://en.wikipedia.org/wiki/MySQL') ?></li>
    <li><?= Html::a('Let\'s Encrypt', 'https://en.wikipedia.org/wiki/Let%27s_Encrypt') ?></li>
    <li><?= Html::a('Font Awesome 5', 'https://en.wikipedia.org/wiki/Font_Awesome') ?></li>
    <li><?= Html::a('AdminLTE Control Panel Template', 'https://adminlte.io') ?></li>
    <li><?= Html::a('Git', 'https://en.wikipedia.org/wiki/Git') ?></li>
</ul>

<h4>Web services</h4>

<ul>
    <li><?= Html::a('GitLab.com', 'https://gitlab.com') ?> - <?= Html::a('OSW page', 'https://gitlab.com/opensourcewebsite-org/opensourcewebsite-org') ?></li>
    <li><?= Html::a('Moqups.com', 'https://moqups.com') ?> - <?= Html::a('OSW page', 'https://app.moqups.com/opensourcewebsite/LMtjCISodJ') ?></li>
    <li><?= Html::a('Cloudflare.com', 'https://cloudflare.com') ?></li>
    <li><?= Html::a('DigitalOcean.com', 'https://m.do.co/c/4d16b1d56809') ?></li>
</ul>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model LoginForm */

use app\models\LoginForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header-data'); ?>
<?php $this->endBlock(); ?>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
            <div class="card-body">
                <p>Please fill out the following fields to login:</p>
                <div class="form-group">
                    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'password')->passwordInput() ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'rememberMe')->checkbox() ?>
                </div>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>
            </div>

            <div class="card-footer">
                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model PasswordResetRequestForm */

use app\models\PasswordResetRequestForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header-data'); ?>
<?php $this->endBlock(); ?>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
            <div class="card-body">
                <p>Please fill out your email. A link to reset password will be sent there.</p>
                <div class="form-group">
                    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                </div>
            </div>

            <div class="card-footer">
                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model ResetPasswordForm */

use app\models\ResetPasswordForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header-data'); ?>
<?php $this->endBlock(); ?>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>
            <div class="card-body">
                <p>Please choose your new password:</p>
                <div class="form-group">
                    <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>
                </div>
            </div>

            <div class="card-footer">
                <div class="form-group">
                    <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */

/* @var $model SignupForm */

use app\models\SignupForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php $this->beginBlock('content-header-data'); ?>
<?php $this->endBlock(); ?>
<div class="row">
    <div class="offset-md-2 col-md-8">
        <div class="card card-primary">
            <div class="card-header">
                <h3 class="card-title"><?= Html::encode($this->title) ?></h3>
            </div>
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <div class="card-body">
                <p>Please fill out the following fields to signup:</p>
                <div class="form-group">
                    <?= $form->field($model, 'email') ?>
                </div>
                <div class="form-group">
                    <?= $form->field($model, 'password')->passwordInput() ?>
                </div>
            </div>

            <div class="card-footer">
                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/team.php
<?php

/* @var $this \yii\web\View */

use yii\helpers\Html;

$this->title = 'Careers and volunteering';
?>
<div class="site-contact">
<p>
OpenSourceWebsite (OSW) exists and succeeds because of the commitments and contributions of our community. We would like to thank everyone who participates in the development and growth of this Website. We’d greatly appreciate input from the community on this.
</p>

<p>
We accepts volunteers and interns who demonstrate appropriate skills and express a strong interest in one or more of the following areas:
</p>

<ul>
    <li>Open data</li>
    <li>Open source development</li>
    <li>Editorial and/or translation work</li>
    <li>UI/UX web design</li>
    <li>Social media and communications</li>
</ul>

<p>
If you are interested in volunteering for OSW, please <a href="/contact">contact</a> us or send a cover letter and your resume to:  team@opensourcewebsite.org.  Your cover letter should describe your areas of interest, your objective in seeking a volunteer experience, and your availability.
</p>

<p>
OSW non-discrimination policy: OSW does not promote or discriminate against any person, population group, or organization with regard to categories protected by international law, as well as other categories identified by the OSW in alignment with our own Human Resources policies. These include, but are not limited to race, color, ancestry, religion, sex, sexual orientation, gender expression, physical appearance, citizenship, marital status, language, education background, national origin, age, disability, and veteran status. We also consider qualified applicants regardless of criminal histories, consistent with legal requirements.
</p>

</div>